### ISSUE TITLE
scons install fails on linux when building lib_full_name

### ISSUE THREAD

**Issue by pmelchior** [rmjarvis/tmv#20]
Redhat linux with static BLAS will give this:
```
$ scons install
scons: Reading SConscript files ...
Using the default scons options
Using compiler: /usr/bin/g++
compiler version: 4.8.5
Determined that there are 8 cpus, but only using 4 jobs to avoid overly high memory use.
You can override this behavior with scons -jN
Debugging turned off
Checking for MKL... no
Checking for ACML... no
Checking for GotoBLAS... no
Checking for CBLAS... no
Checking for ATLAS... no
Checking for Fortran BLAS... yes
Using Fortran BLAS
Using OpenMP
TMV Version  $HeadURL$

TypeError: not enough arguments for format string:
  File "/n/home00/melchior.12/code/tmo/tmv-0.72/SConstruct", line 1431:
    SConscript(script_files, exports=['env'])
  File "/n/home00/melchior.12/lib/scons-2.4.1/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/n/home00/melchior.12/lib/scons-2.4.1/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/n/home00/melchior.12/lib/scons-2.4.1/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/n/home00/melchior.12/code/tmo/tmv-0.72/src/SConscript", line 134:
    lib_full_name = os.path.join(GetBuildPath('#lib'),'libtmv.so.%s.%s'%version)
```

The failure is clear: in line 134, the string has two `%s` but only one variable to feed them. I fixed it by replacing it with
```
    lib_full_name = os.path.join(GetBuildPath('#lib'),'libtmv.so.%s.%s' % (version,0))
```
The same happens in line 141, i.e. whenever `_full_name` is being built. With this "fix", the installation runs fine.

**Comment by rmjarvis** [comment]
The problem here is actually in the tmv-version file.  This was an elaborate setup to get the version automatically from the SVN branch.  Now that I'm using git, that was invalid, so it gave the version as $HeadURL$, which isn't right.  

It should work correctly if you use the [installation instructions still over at Google Code](https://code.google.com/archive/p/tmv-cpp/wikis/Installation.wiki).  And I've fixed this on master here: 685845033cf4c24ac9417c1f3edec0372a7376ec, so it should work for the next release, v0.73 (which should be soon, I might add).
