### ISSUE TITLE
Error building with g++-6 and OpenMP

### ISSUE THREAD

**Issue by dpo** [rmjarvis/tmv#22]
OSX 10.9. I'm trying to update the Homebrew formula for `tmv`. All is well with clang++, but g++-6 produces the error:

```
In file included from tests/TMV_TestVector.cpp:2:0:
tests/TMV_TestVector.cpp: In function 'void TestVectorIO()':
tests/TMV_Test.h:75:21: error: cannot convert 'std::ofstream {aka std::basic_ofstream<char>}' to 'bool' for argument '1' to 'void DoAssert(bool, std::__cxx11::string)'
         DoAssert(x,s); \
                     ^
```

**Comment by rmjarvis** [comment]
Thanks for the report.  I'm not even sure if I've tried TMV with g++-5 yet, but I certainly haven't tried g++-6.  Do you need to use the bleeding edge compiler?  Or can you (for now, until I get around to working on this) have the brew formula use g++-4.x where I know everything is copacetic?

**Comment by dpo** [comment]
Thanks for the quick reply. In Homebrew, the default gcc, which is the only compiler currently supporting OpenMP, is gcc-6.2, so I can't really downgrade. I presume the stream must be cast as a bool somehow, but my c++ is virtually inexistent.

**Comment by rmjarvis** [comment]
Is there a good threaded LAPACK option in Homebrew?  (Or can you use the one that Apple ships?)

If so, you can just enable LAPACK for TMV (which is not the default, but is easy: `scons WITH_LAPACK=true`) and I think that would cover all of the threading advantages that OpenMP would have given you.  In which case, you could probably use clang instead without taking much of a multithreading performance hit.

Aside from the threading consideration, the tradeoffs between using or not using LAPACK in TMV are minor.  Most algorithms are the same natively in TMV as what LAPACK provides (which is why it's not turned on by default).  A couple things (QRP decomposition, QR update and downdate -- I forget what else) are a bit faster with the TMV code.  And hermitian svd is a bit faster with the LAPACK code.  Probably you won't notice much difference for typical use cases.

So if LAPACK lets you get good threading with clang, it's probably a win, at least until I try out g++-6 and fix the compiler issues.  (FWIW, I suspect there will be more than just this one compile error.  They switched the default mode to use C++-14, and most of the TMV code was written before there was such a thing, so there will probably be other issues than this to deal with.)

**Comment by dpo** [comment]
Thanks. I've already enabled `WITH_LAPACK=true`, so I'll go with that until you can give g++-6 a go.

Good luck!

**Comment by rmjarvis** [comment]
I believe I have everything working with all the various C++ standards now.  v0.74 should work with c++11, c++14, and c++17.
